[package]
name = "life"
version = "0.1.0"
authors = ["Oivvio Polite <oivvio@polite.se>"]
edition = "2018"

[dependencies]
lifelib = { path = "lifelib" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
